version: 2.1

executors:
  ruby-executor:
    docker:
      - image: circleci/ruby:3.0.0
    working_directory: ~/myapp

jobs:
  build:
    docker:
      - image: circleci/ruby:3.0.0
      - image: circleci/postgres:13  # Add PostgreSQL service
        environment:
          POSTGRES_USER: rails
          POSTGRES_DB: myapp_test
          POSTGRES_PASSWORD: rails
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            gem install bundler
            bundle install
      - run:
          name: Set up database
          command: |
            if [ -f config/database.yml.circleci ]; then
              cp config/database.yml.circleci config/database.yml
            else
              echo "Warning: config/database.yml.circleci does not exist. Using default config."
            fi
            RAILS_ENV=test bundle exec rake db:create db:schema:load
      - run:
          name: Run tests
          command: |
            RAILS_ENV=test bundle exec rspec
      - run:
          name: Run linting
          command: |
            bundle exec rubocop

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
