version: 2.1

executors:
  ruby-executor:
    docker:
      - image: circleci/ruby:3.0.3  # Ruby 3.0 image
    working_directory: ~/myapp

jobs:
  build:
    executor: ruby-executor
    steps:
      - checkout  # Check out the code from the repository
      - run:
          name: Install dependencies
          command: |
            gem install bundler
            bundle install
      - run:
          name: Set up database
          command: |
            cp config/database.yml.circleci config/database.yml  # Use CircleCI-specific database config if needed
            RAILS_ENV=test bundle exec rake db:create db:schema:load
      - run:
          name: Run tests
          command: |
            RAILS_ENV=test bundle exec rspec  # Replace with your test command if different
      - run:
          name: Run linting
          command: |
            bundle exec rubocop  # Run your linter

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
